### ISSUE TITLE
Why don't update the dependent formula "llvm@12" to "llvm"?

### ISSUE THREAD

**Issue by PumpkinDemo** [kframework/homebrew-k#11]
`brew --prefix llvm` will be `/usr/local/opt/llvm`,
But if brew install `llvm@12`, the actual path would be like `/usr/local/opt/llvm@12`.
and this leads to an error when using `kompile`
```
/usr/local/lib/kframework/../../bin/llvm-kompile: line 39: /usr/local/opt/llvm/bin/opt: No such file or directory
[Error] Critical: llvm-kompile returned nonzero exit code: 1
```
Although there is a mitigation, that I can just create a symlink, but it's not a final solution in my opinion.

Perhaps is there any reason for stay with `llvm@12`?

**Comment by Baltoli** [comment]
There is at least one known issue with LLVM 13 that currently breaks the K Haskell backend, unfortunately.
